# https://services.shopify.io/services/camus/production
org_line: Data Science & Engineering
director: davidlennie
owners:
- Shopify/data-acquisition
classification: tier2
security:
  data_management:
    contains_pii: false # Transmits it to data warehouse but doesn't store any
